version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    cooldown:
      default-days: 5
    commit-message:
      prefix: "build"
      include: scope
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    commit-message:
      prefix: "ci"
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/tests/e2e"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    commit-message:
      prefix: "ci"
      include: scope
    groups:
      python-dependencies:
        patterns:
          - "*"
