sonar.projectKey=dantte-lp_ypcli
sonar.organization=dantte-lp

sonar.sources=.
sonar.exclusions=**/*_test.go,cmd/**,docs/**,dist/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
